### ISSUE TITLE
Getting color of Text Object doesn't work.

### ISSUE THREAD

**Issue by deonix37** [RhenaudTheLukark/CreateYourFrisk#1]
The documentation says:

> **Text.color** – Get or set the color of the text...

Getting color doesn't work.
Example: Text.color[3] should return third value of text but it results in an error:
"Attempt to index a nil value".

CYF version: 1.0 for Windows 64-bit.

**Comment by RhenaudTheLukark** [comment]
I tested that code snippet:

`maintext = CreateText({"[novoice]Hi"}, {400, 99}, 320, "Top", 100)
maintext.color = {1, 0, 0}
local str = "{ "
for i = 1, #maintext.color do
    str = str .. maintext.color[i] .. (i == #maintext.color and " " or ", ")
end
DEBUG(str.. "}")`

and it returned me "{ 1, 0, 0 }" as wanted. 

As I can't reproduce that error, I will say it was an error on your end. I'll let it open a bit more if you want to add something, but that bug currently is closeable.

**Comment by deonix37** [comment]
Looks like I can't get color before setting it. I expected that it would return me 1 as each value, as default color is white, but it seems like I must set it to something before retrieving it.
Thank you.
