### ISSUE TITLE
Mac version doesn't work

### ISSUE THREAD

**Issue by TheMan3530** [RhenaudTheLukark/CreateYourFrisk#102]
Upon opening the application on mac, I am given the error message "You do not have permission to open the application “Create Your Frisk 0.6.5”". Please fix.

**Comment by RhenaudTheLukark** [comment]
Run these commands:

    sudo chmod +x "Create Your Frisk 0.6.5.app"
    sudo chmod +x "Create Your Frisk 0.6.5.app/Contents/MacOS/Create Your Frisk 0.6.5"
