### ISSUE TITLE
The application “Create Your Frisk 0.6.5” can’t be opened.

### ISSUE THREAD

**Issue by rbxq** [RhenaudTheLukark/CreateYourFrisk#106]
I'm on an M1 mac Monterey, and I get this popup whenever i try to open CreateYourFrisk for mac.

**Comment by RhenaudTheLukark** [comment]
It's most likely because CYF doesn't have a permission to be opened on your computer.

Try to open a command prompt in the same folder as CYF and run those command lines:

    sudo chmod +x "Create Your Frisk 0.6.5.app"
    sudo chmod +x "Create Your Frisk 0.6.5.app/Contents/MacOS/Create Your Frisk 0.6.5"
    
with "Create Your Frisk 0.6.5.app" being the name of the CYF executable, change it to the name yours has if needed.

**Comment by rbxq** [comment]
> It's most likely because CYF doesn't have a permission to be opened on your computer.
> 
> Try to open a command prompt in the same folder as CYF and run those command lines:
> 
> ```
> sudo chmod +x "Create Your Frisk 0.6.5.app"
> sudo chmod +x "Create Your Frisk 0.6.5.app/Contents/MacOS/Create Your Frisk 0.6.5"
> ```
> 
> with "Create Your Frisk 0.6.5.app" being the name of the CYF executable, change it to the name yours has if needed.

I get this:
chmod: Create Your Frisk 0.6.5.app: No such file or directory
chmod: Create Your Frisk 0.6.5.app/Contents/MacOS/Create Your Frisk 0.6.5: No such file or directory

**Comment by RhenaudTheLukark** [comment]
If you get this error, it means you haven't used the right name for CYF's app in the two command lines I sent you...

Could I please get a screenshot of the folder which has CYF in it?

**Comment by rbxq** [comment]
Sorry, ive got it now, im just mildly incompetent.

**Comment by LE0-Droid** [comment]
how do you "open a command prompt"
