### ISSUE TITLE
text object skipping problem

### ISSUE THREAD

**Issue by deonix37** [RhenaudTheLukark/CreateYourFrisk#11]
If you have a text object with lines that have [noskip] in them, and you press X fast enough at the beginning of the lines, then there is a big chance you'll skip them.

**Comment by RhenaudTheLukark** [comment]
This is why you use [noskip] in the very beginning of the text

**Comment by deonix37** [comment]
Yep, you can still skip them

**Comment by RhenaudTheLukark** [comment]
After multiples and unending tries, I couldn't bypass [noskip]
