### ISSUE TITLE
The build.py wont work

### ISSUE THREAD

**Issue by jmxamongusmodder** [RhenaudTheLukark/CreateYourFrisk#110]
**Describe the bug**
  File "C:\Users\thinkagainsucka\Downloads\CreateYourFrisk-0.6.6.1\CreateYourFrisk-0.6.6.1\Build.py", line 30
    print("Creating \"bin\" folder...", end="")
                                                              ^
SyntaxError: invalid syntax

**To Reproduce**
1. just do it

**Expected behavior**
I thought it would buildlldldl

**Screenshots**
![epicerror](https://user-images.githubusercontent.com/80003646/176088627-778fd0dc-a0ce-49ed-870b-01540bc9bd8f.PNG)

**Setup (please complete the following information):**

 - OS: windows
 - Version latest
- Mod dont have one

**Comment by Dobby233Liu** [comment]
What Python version are you using? In case you want to, you can download the already built 64 bit windows version of 0.6.6.2 [here](https://cdn.discordapp.com/attachments/988090379205247066/988118640681443348/CYF_v0.6.6_LTS_2_-_Windows_64-bit.zip) or 0.6.6.1 [here](https://github.com/RhenaudTheLukark/CreateYourFrisk/releases/download/v0.6.6.1/CYF.v0.6.6.LTS.1.-.Windows.64-bit.zip), those builds are linked in the [Releases](https://github.com/RhenaudTheLukark/CreateYourFrisk/releases) page

**Comment by LucasCTN** [comment]
You are probably using Python 2 instead of Python 3 to run the script. The way to use `print()` is different.

**Comment by RhenaudTheLukark** [comment]
I will assume it's been fixed, if it hasn't feel free to open again!
