### ISSUE TITLE
Getting an error message.

### ISSUE THREAD

**Issue by beans-bonfire** [RhenaudTheLukark/CreateYourFrisk#113]
**Describe the bug**
Whenever I'm playing a game with dialogue outside of battle, I get an error message saying at line 117, there was an error with the "animation.lua" file.
**To Reproduce**

**Expected behavior**
What I expected was for the game to keep going.
**Screenshots**

**Setup (please complete the following information):**
 - OS: [e.g. Windows, Linux, Mac]
 - Version [e.g. 0.6.1.2]
- Mod (Please upload it and send a link)

**Additional context**

**Comment by RhenaudTheLukark** [comment]
I don't think that's a CYF problem, more like a mod problem. How about you reach out to the mod's creator instead?
