### ISSUE TITLE
Inaccuracies

### ISSUE THREAD

**Issue by dl-tg** [RhenaudTheLukark/CreateYourFrisk#114]
1) The FIGHT button should return to Default animation once the Target appears, after you select the enemy.
Same with ACT and ITEM, after you use an item/act - respective button should resort to default animation
2) The damage text (counter that appears above green health bar after you hit the enemy) has wrong animaton. 
It's too smooth, slow and goes way too high. Health bar decreasing also seems to be too slow
3) Heart's Y position seems to be slightly too high when choosing the menu item (act/item).
The X position seems to be also weird. The space between the item and heart looks too big (pic for reference):
![image](https://user-images.githubusercontent.com/90642859/208420162-c56f9c67-e824-4499-b7be-d1e152050c7e.png)

**Comment by RhenaudTheLukark** [comment]
Hey there! To be honest, CYF isn't really built for accuracy toward Undertale.
Stuff such as the text being at half speed compared to Undertale's is also a problem that hs been reported before, but I believe the project is in a "good enough" state to be considered an Undertale engine.
That being said, the first point is fair, and I will try to address it, as it will most likely look better if the button goes back to its default state after the main player choice is made.
