### ISSUE TITLE
text command [func} is always called from encounter script, not source script

### ISSUE THREAD

**Issue by CheBuRex** [RhenaudTheLukark/CreateYourFrisk#116]
In my case it was used in HandleCustomCommand in enemy script 
but it was calling the function from encounter script

![image](https://github.com/RhenaudTheLukark/CreateYourFrisk/assets/58214901/207431a8-f8e0-4fb7-a523-2277ab55e176)

**Comment by CheBuRex** [comment]
ik that it's unstable build but i think i should to report a bug, shouldn't i?

**Comment by RhenaudTheLukark** [comment]
If you used [func] in a text in the BattleDialog() function, then [func] will call the function in the script the arena text object belongs to, which is the Encounter script!

**Comment by CheBuRex** [comment]
Oh, ok. I just was wondering because in LTS2 it was behaving differently.

**Comment by RhenaudTheLukark** [comment]
Was it now? With BattleDialog()? That seems more like a LTS2 error than anything to me, I'll check that on my end.

**Comment by CheBuRex** [comment]
Yes, it was calling function from source script when used in BattleDialog()

**Comment by RhenaudTheLukark** [comment]
You would be right! I will jolt that down and add it to my TODO list!
Will close and cite this issue when it's done!

**Comment by RhenaudTheLukark** [comment]
The latest commit should fix this issue, a new version of CYF with those latest changes should spring up in about 10m, feel free to check it out and close this issue if the problem's gone!
