### ISSUE TITLE
Wave Timer isn't frame based

### ISSUE THREAD

**Issue by M3Dasher** [RhenaudTheLukark/CreateYourFrisk#120]
**Describe the bug**
The wave timer uses real time (possibly delta time), and not frame based, so if the game lags and slows down, the wave timer doesn't.

**To Reproduce**
1. Spawn several projectiles and/or sprites inside a wave to cause a large frame drop
2. Wait

**Expected behavior**
The wave timer slows down with the frames to wait until the end of the wave, like Frame Based.

**Setup:**
 - OS: Windows 8
 - Version 0.6.6 LTS 3
- Mod: Any (apologies if this is a problem, i will add it  later if necessary.)

**Additional context**
I did this on a sans mod intro attack, and it stopped faster than it should have.
The solution? Make it frame based!
I made the original wave timer extremely long and then used a variable that, when high enough, calls EndWave().

**Comment by RhenaudTheLukark** [comment]
The usual alternative is to not use wavetimer at all, setting it to math.huge (infinity), and ending the wave yourself after your wave is done! I suggest doing that instead of changing a system that's been around for a decade and that many other waves have been using so far!

**Comment by M3Dasher** [comment]
okay, thank you
