### ISSUE TITLE
Request: Audio.StopSound()

### ISSUE THREAD

**Issue by M3Dasher** [RhenaudTheLukark/CreateYourFrisk#121]
Audio.StopSound(filename)
Stops all sounds that are playing _filename_

**Why did you want this?**
1. To quiet down the gaster blasters, so only one charge and fire sound plays.
2. Allows people to make sounds work just like Undertale (gamemaker), where if you play an audio that is still playing, it stops and plays again.

(I researched both of these by looking at sans' special attack, where the blaster charge sounds cut off when a new one spawns, and the same thing happens with the actual blast sound.)

**Example of use**
```lua
--[[
Stop all previous sounds playing "hotdog" and then play it again.
Now if the sound plays every frame, they don't overlap.
]]--
Audio.StopSound("hotdog")
Audio.PlaySound("hotdog")
```

**Comment by RhenaudTheLukark** [comment]
Instead, I suggest you use the NewAudio object, which allows you to do exactly that! You can handle one or several sound channels, and play the sound again from it to override the previous time it was played!

**Comment by M3Dasher** [comment]
> Instead, I suggest you use the NewAudio object, which allows you to do exactly that! You can handle one or several sound channels, and play the sound again from it to override the previous time it was played!

oh, i didn't even know that existed in the documentation, i'll take a look at it. thank you!
