### ISSUE TITLE
[Suggestion] Optimizations

### ISSUE THREAD

**Issue by xXxToxicBlueDustxXx** [RhenaudTheLukark/CreateYourFrisk#14]
As the title says, it would be good to make CYF work the same as Unitale in terms of performance because for example in the overworld the character goes very slow like a snail, apart from that in some battles is slow but other fast, another example is the of the posseour that in that performance is decent, but when you use certain attacks the performance goes down.

PC Specs:

Ram: 2 Gb
Processor: Intel(R) Atom(TM) CPU N2100   @ 1.60GHz, 1600 Mhz
Graphics:  Intel(R) Graphics Media Accelerator 3600 Series
Shader Model: 3.0

I know that is not a priority for now, but it would be good if the performance is improved a bit so that it works as Unitale, in terms of performance for PCs like the one I have

**Comment by RhenaudTheLukark** [comment]
The slowness of the character is not dependent from the frames per second, it actually is dependent from the speed of the character itself.

In the code, the character goes at 2 frames per second, I think, the same speed as the soul in battles.

However, maybe that for such bigger environment, it'd be best to increase that value.

If you want to, the speed of the character is a variable in the PlayerOverworld class, which normally is in the Scripts/Overworld folder.

You can try to play with it and see if it solves your problem :)

**Comment by xXxToxicBlueDustxXx** [comment]
let me check it whit fraps to see the fps

**Comment by xXxToxicBlueDustxXx** [comment]
well in the Main Screen ( Where You Decide to Go to Overworld or to ModDev) The FPS are 21 -14
in the story intro the FPS are: 18 - 14
after the Story intro: FPS 9 -4
and in the Overworld: 7 - 6,5

In Soul Battle (Using the Encounter Example):
same has the Over world

if is loaded trough the ModDev: 18 - 14 but when a bullet appear the FPS goes Down

**Comment by xXxToxicBlueDustxXx** [comment]
its me, or the Action Buttons its suppose to be blurred?
[https://i.imgur.com/UepYM3b.jpg](url)

**Comment by RhenaudTheLukark** [comment]
Okay, so.
Maybe it'd be great to make so CYF doesn't need that much resource, indeed.

Your FPS indeed seem kinda low, but if you're on Unity, I have to tell you Unity by itself takes a lot of RAM.

If you play on the Standalone version of CYF, you'll see there's a very big FPS difference.

Then, for the Action Buttons being blurred, I remember it was because of a shader problem some people had. I thought it was solved...it seems not lol.

Although, 21 FPS on the Title screen... You really should try the Standalone version, maybe your computer can't handle Unity at this point.

**Comment by xXxToxicBlueDustxXx** [comment]
sorry for bein a little annoying but you will give a link to standalone vercion??

**Comment by RhenaudTheLukark** [comment]
Yeah, sure.
However, the last one is not totally up to date, but you can make one very easily by just doing so:

On the tool bar, click the "File" button, then select the "Build Settings..." option.
A new window will open. There will be a list of OSes under the "Target Platform" dropdown: choose the one you are using.
If possible, select the architecture you are using.
Finally, press the "Build" button.
When the build will be finished, you'll have the Standalone.
All you need to do is to copy the "Default" and "Mods" folders in the folder containing the Standalone, and here, you have it :)

Hopefully I could help you. I also suggest you to join this community's subreddit (https://www.reddit.com/r/Unitale/) or Discord server (https://discord.gg/0c8fN7KCwBh4ZBL9) if you want to, there are nice people over there :P
