### ISSUE TITLE
Pausing text boxes using waitfor shows extra characters

### ISSUE THREAD

**Issue by WD200019** [RhenaudTheLukark/CreateYourFrisk#16]
**CYF Version: v0.6.1.1**

There is an issue I encountered while messing with text objects (but it works with enemy dialogue too).
Whenever text is paused by using `waitfor`, then, based on the text's speed (`waitall` and `w` commands do not make a difference), additional characters will be shown, ones that come after the `waitfor` call.

**How to reproduce**

- Make a new encounter for testing
- Either create a text object, or set the enemy's dialogue (it works for both)
- Enter some test text (For example, I used: `Text_text_text[waitfor:C]_Test_test_test`
- Load up the mod, and navigate to when the text starts to type

**Result**

Extra characters are typed based on `speed`, which is 1 by default.

For example, `Text_text_text[waitfor:C]_Test_test_test` will display **`Text_text_text_`** instead of **`Text_text_text`**

Changing the text's `speed` also gives a different outcome: 

`[speed:2]Text_text_text[waitfor:C]_Test_test_test` will show **`Text_text_text_T`**.
`[speed:6]` will show **`Text_text_text_Tes`**, and more extra characters will be shown with faster text.

Again, applying any `w` or `waitall` commands will do nothing but slow down the text, it will still go on to type out extra characters.

**Comment by RhenaudTheLukark** [comment]
Fixed, not only for `waitfor` and `speed` but also for `waitfor` and `letters`, hopefully no error like this will happen in the future.
