### ISSUE TITLE
Scaling glitches

### ISSUE THREAD

**Issue by Neroctopus** [RhenaudTheLukark/CreateYourFrisk#17]
Once I used a rescaling of my bullet(yscale only) and I got a little surprise, At first it perfectly worked...But then after the third time the attack was appearing, sometimes, the yscaling was to 1 or even 0 and there is no problem in my script, I am 100% sure of that...(I'm using 0.6.1.1 windows 64 version)

**Comment by RhenaudTheLukark** [comment]
It'd be good if you could send me this script on Discord so I can see if your script really is flawless or not.

**Comment by Neroctopus** [comment]
Ok I'll send it later, when I'll be on my computer

**Comment by RhenaudTheLukark** [comment]
I'll need all the files related to the wave to be able to test it, including sprites...

**Comment by RhenaudTheLukark** [comment]
After no answer or anything new, this issue is closed
