### ISSUE TITLE
DEBUG function doesn't work when called with [func].

### ISSUE THREAD

**Issue by deonix37** [RhenaudTheLukark/CreateYourFrisk#2]
Example:
```
text_var = "The text[func:Test]"
function Test()
  DEBUG("Debugging text.")
end
```
Debug won't display in this or similar cases.

CYF version: 1.0 for Windows 64-bit.

**Comment by RhenaudTheLukark** [comment]
May I have more information about what you did, and which text object got that [func]?

Text objects launch functions in the script they are created in, te main arena text launches its functions from the Encounter script and monster texts launch their functions in their corresponding enemy scripts as a reference.

Check if you followed that pattern.

**Comment by deonix37** [comment]
Sorry for my inattention. I realized my mistake. The function was in a wrong script.
