### ISSUE TITLE
[next] not working for text object

### ISSUE THREAD

**Issue by Filmos** [RhenaudTheLukark/CreateYourFrisk#25]
**Bug description**
In text objects (created by `CreateText()`) `[next]` is completely ignored (same goes for `[finished]` and `[nextthisnow]`, but I assume those are only related to enemy dialog). 

**Code to reproduce**
```lua
Text = CreateText({"This is[next]","text that","should automatically change"},{320, 240},150,"Top",150)
Text.progressmode = "manual"
```

**Workaround**
If anyone else is struggling with this, there is a workaround for it. You have to create a global variable where the text object is stored as well as a function which has `.NextLine()` inside of it. While it is a working solution, it is required to create a variable and function for each and every text object (when you want to display more than one at once), extremely cluttering the code.
```lua
local Text
function PseudoNext()
  Text.NextLine()
end
Text = CreateText({"This is[func:PseudoNext]","text that","should automatically change"},{320, 240},150,"Top",150)
Text.progressmode = "manual"
```

**Setup:**
 - OS: Windows
 - Version: 0.6.1.2

**Comment by RhenaudTheLukark** [comment]
We'll look into it right now!

**Comment by RhenaudTheLukark** [comment]
Fixed in the last commit to master!
