### ISSUE TITLE
NewAudio.GetVolume() doesn't work properly.

### ISSUE THREAD

**Issue by deonix37** [RhenaudTheLukark/CreateYourFrisk#3]
Example:

> NewAudio.CreateChannel("a_normal_channel")
> NewAudio.SetVolume("a_normal_channel", 0.5)
> NewAudio.GetVolume("a_normal_channel")

NewAudio.GetVolume() will always return 1, though the volume actually was changed.

CYF version: 1.0 for Windows 64-bit.

**Comment by RhenaudTheLukark** [comment]
You are right, it seems NewAudio.GetVolume() returns the pitch instead. My bad.
