### ISSUE TITLE
Not working for Mac

### ISSUE THREAD

**Issue by SoshJam** [RhenaudTheLukark/CreateYourFrisk#33]
**Describe the bug**
It said in the README that this error was fixed, but I'm still getting it.
The error: `error in script CYF's startup: The engine detected no mods folder in your files; are you sure it exists?`

**To Reproduce**
Just start it on Mac.

**Expected behavior**
The program would open.

**Screenshots**
<img width="641" alt="screen shot 2018-11-21 at 10 06 06 am" src="https://user-images.githubusercontent.com/21060092/48857004-1ee3c400-ed75-11e8-991a-d85c226f0dea.png">

**Setup (please complete the following information):**
 - OS: Mac OS X Mojave
 - Version: 0.6.1.2
 - Mod: None, happens on startup

**Additional context**
Do I need to download/install a dependency like Python or something?
**EDIT:** I installed the latest version of Python, but it didn't help.

**Comment by WD200019** [comment]
You're correct that this doesn't work currently, you're not the only one. We're looking into it!

In the meantime, a work-around has been found: Download the prior version, 0.6.2, and move the "Mods" and "Default" folders inside of "Create Your Frisk v0.6.2.app". Hope this helps until this can be solved for real!

**Comment by SoshJam** [comment]
I built it from the source code and its working fine now. Thanks for the help though!

**Comment by RhenaudTheLukark** [comment]
I just replaced the version of Mac for v0.6.2.1! Download it again, now it should work well! Closing this thread :P
