### ISSUE TITLE
Hitbox scaling is incorrect in full screen mode

### ISSUE THREAD

**Issue by Windblade-GR01** [RhenaudTheLukark/CreateYourFrisk#34]
**Describe the bug**
Hitbox scaling is incorrect in full screen mode.

**To Reproduce**
Press H while in fullscreen mode.

**Expected behavior**
The hibox display would scale with screen size.

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows, Linux,
 - Version: 0.6.1.2

**Additional context**
This is caused because the hitbox display do not scale with the canvas.

**Comment by RhenaudTheLukark** [comment]
We know, but as it is only a debug feature, I don't think it's that important

**Comment by Windblade-GR01** [comment]
Anyways this a bug, it's low priority but that's no reason to ignore it. Label it as a bug and low priority.

**Comment by RhenaudTheLukark** [comment]
Fixed in 0.6.2.2
