### ISSUE TITLE
[Issue] Not matched [ in TextObject freezes up CYF

### ISSUE THREAD

**Issue by Filmos** [RhenaudTheLukark/CreateYourFrisk#35]
**Describe the bug**
If text used in TextObject contains more `[` than `]` (so, there are some `[` that are not matched), CYF will freeze up and go unresponsive when trying to display it. This doesn't happen for encounter or enemy text.

**Code To Reproduce**
```lua
CreateText({"[abc"}, {320, 240}, 150)
```

**Expected behavior**
Not only shouldn't it freeze up, but it shouldn't throw any error at all. It should simply display the `[` and the following text, just like it does in encounter/enemy text.

**Setup:**
 - OS: Windows
 - Version 0.6.2.1

**Comment by SoshJam** [comment]
Try escaping it, e.g. `CreateText({“\[abc”},` etc.

**Comment by RhenaudTheLukark** [comment]
Fixed in 0.6.2.2
