### ISSUE TITLE
[Issue] Incorrect documentation of [speed] and issues with it

### ISSUE THREAD

**Issue by Filmos** [RhenaudTheLukark/CreateYourFrisk#37]
**Describe the issue**
The documentation states that:
![image](https://user-images.githubusercontent.com/21157064/48865475-05bc3100-edd0-11e8-92c8-d83a36b9ef19.png)
However, when at `[speed:1]`, 1 character is being displayed, but every 4 frames. 

**Consequences**
Now, it's not only a mistake in the documention. This has some pretty far going consequences. 
Firstly, setting speed to 2 doesn't make it display 1 character every 2 frames, but instead displays 2 characters every 4 frames, making the text less smooth.
Secondly, since `[speed]` can only use integers, precision of it is significantly decreased (it actually makes it impossible to match the exact text speed of Deltarune).
It's also worth noting that, since text speed can't be lower than 1, making the text display slower than normally is only obtainable by putting `[w]` between every character.

**Final notes**
Similiar problems would occur with `[letters]`, since it also displays n characters per "frame". That means that any fixes for `[speed]` should also be applied to `[letters]`.

**Setup:**
 - OS: Windows
 - Version 0.6.2.1

**Comment by Filmos** [comment]
What I was referring to was that it runs faster than speed 1 (1 character every 4 frames) and slower than speed 2 (1 character every 2 frames), meaning it displays 1 character every 3 frames, which in current speed notation would be 1.5.

**Comment by RhenaudTheLukark** [comment]
Fixed in 0.6.2.2
