### ISSUE TITLE
Game Over screen [func] causes an error

### ISSUE THREAD

**Issue by VMan-2002** [RhenaudTheLukark/CreateYourFrisk#39]
**Describe the bug**
When using a [func:funcname] call in a game over screen the engine errors with the text "Func called but no script to reference. This is the engine's fault, not yours."

**To Reproduce**
Add "[func:funcname]" into part of the variable "deathtext"

**Expected behavior**
The function is called in the scope of the Encounter.

**Comment by RhenaudTheLukark** [comment]
Interesting. I think I know where it comes from, but I will have to remake the GameOver scene's behavior if I want to pull this off. @WD200019 and I will look into it to hopefully make it work in a future release!

**Comment by RhenaudTheLukark** [comment]
Fixed in 0.6.2.2
