### ISSUE TITLE
SetButtonLayer(layer) not working as intended

### ISSUE THREAD

**Issue by KodirovGD** [RhenaudTheLukark/CreateYourFrisk#40]
**Describtion**
Probably a minor issue but issue none the less.
SetButtonLayer(layer) function sets the layer of player name, lv and hp but not the layer of the FIGHT, ACT, ITEM and MERCY buttons as implied in the documentation and function name itself.

**To Reproduce**
1. Make bg file in Sprites folder see-through (fully back with alpha32 being 166 in the screenshot below)
2. Put this in your encounter script: 
`function EncounterStarting()
 SetButtonLayer("Bottom")
end`
3. Launch the encounter

**Expected behavior**
The buttons were expected to have a black tint but the name, lv and hp have this tint instead.

**Screenshot**

![image](https://user-images.githubusercontent.com/45706822/49684933-dbff4b80-faeb-11e8-9be7-5db93b02c7bf.png)

**Setup:**
 - OS: Windows
 - CYF version 0.6.2.1
- Mod: [MinorBugExample.zip](https://github.com/RhenaudTheLukark/CreateYourFrisk/files/2659604/MinorBugExample.zip)

**Comment by KodirovGD** [comment]
CYF version 6.2.1 has the same issue

**Comment by RhenaudTheLukark** [comment]
Fixed in 0.6.2.2
