### ISSUE TITLE
I (am) very stupid

### ISSUE THREAD

**Issue by getkirill** [RhenaudTheLukark/CreateYourFrisk#44]
how to run/install Create Your Frisk?
(yes, i (am) stupid)

**Comment by WD200019** [comment]
You don't install it. You download it from the [releases page](https://github.com/RhenaudTheLukark/CreateYourFrisk/releases), choose the zip for your OS, download it and extract it. Then you just open the .exe, .app or .x86_64 file depending on your OS.
