### ISSUE TITLE
The new File object can't use ".."

### ISSUE THREAD

**Issue by AlonEve** [RhenaudTheLukark/CreateYourFrisk#48]
As written when you try to go to an upper folder in CYF the use of the text ".." is forbidden... so you can't escape to a different folder.
but if you have a file that has ".." in it's name it wont let you use it either...
it may be practical if you need to load a file that has a name which ends with a dot, and then there is another dot for the extension.

**Comment by WD200019** [comment]
All right, fair enough. We didn't want to take any chances at all. Just try to avoid this naming convention for now.

**Comment by RhenaudTheLukark** [comment]
I don't really see why someone would add ".." to a file name. But in any case, yes, we don't want to take any chances, the goal is and as always been to sandbox the engine to forbid the access to files the modder shouldn't have access to
