### ISSUE TITLE
Overworld bugs.

### ISSUE THREAD

**Issue by deonix37** [RhenaudTheLukark/CreateYourFrisk#5]
Good news: this is the last bug report.
Bad news: overworld freezes sometimes after winning some random encounters or transitioning to other locations. By freezing I mean that it is just a black screen and nothing else. It happens almost every time.
Also, after entering any encounter the screen goes windowed if it was fullscreened (the same thing applies to modDev). And yeah, this is the default overworld, not a custom one.

**Comment by RhenaudTheLukark** [comment]
I may need more info about that bug.

Do you have any bug stack trace in the output_log.txt file? I think it is now in %APPDATA%/LocalLow/Nobody's Getting Paid Here/Create Your Frisk

**Comment by deonix37** [comment]
Sure
[output_log.txt](https://github.com/RhenaudTheLukark/CreateYourFrisk/files/1340523/output_log.txt)

**Comment by RhenaudTheLukark** [comment]
Okay, I see.

```
NullReferenceException: Object reference not set to an instance of an object
  at UnitaleUtil.GetCurrentOverworldAudio () [0x00000] in <filename unknown>:0 
  at PlayerOverworld.RestartMusic () [0x00000] in <filename unknown>:0 
  at PlayerOverworld+<ShowOverworld2>c__Iterator5.MoveNext () [0x00000] in <filename unknown>:0 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) [0x00000] in <filename unknown>:0 
```

It is the bug, and I know where it is from.

What version are you using? 0.x (closed) or 1.x (open)?

**Comment by deonix37** [comment]
1.0

**Comment by RhenaudTheLukark** [comment]
So on Unity, gotcha.

I will take a greater look tomorrow.

**Comment by deonix37** [comment]
btw, pressing F4 doesn't make CYF go fullscreen. It only quits fullscreen.
