### ISSUE TITLE
CYF fails to show screen output on linux

### ISSUE THREAD

**Issue by daniel071** [RhenaudTheLukark/CreateYourFrisk#66]
**Describe the bug**
When running the Linux 64bit executable file for CYF 0.6.4, the program runs but outputs just a black screen. When I press Z and go into the mod, I can hear the background music playing and the colour changes.

**To Reproduce**
1. Go to https://github.com/RhenaudTheLukark/CreateYourFrisk/releases/tag/v0.6.4 and download the _CYF.v0.6.4.-.Linux.64-bit.zip_ version
2. Extract the zip
3. Give the .x86_64 file execution permission
4. Run it

**Expected behavior**
I expected the title screen to show up that asks you if you want to go to overworld or mods.

**Screenshots**
When I first start CYF:
![When I first start CYF](https://raw.githubusercontent.com/daniel071/images-for-readme/master/Screenshot%20from%202020-02-11%2017-45-12.png)

When I press Z a couple of times:
![When I press Z a couple of times](https://raw.githubusercontent.com/daniel071/images-for-readme/master/Screenshot%20from%202020-02-11%2017-46-06.png)

**Setup:**
 - OS: Manjaro Linux
 - Desktop Environment: Gnome 3.34.2
 - Linux Kernel version: Linux 5.4.18-1-MANJARO
 - CYF Version: 0.6.4

**Additional context**
I've tried older versions of CYF and the 32 bit version of CYF and they both result in the same error

**Comment by WD200019** [comment]
Do you have any of: `libglu1-mesa`, `libxcursor2` and `libxrandr2` installed? Also try running the `.x86`, and also try using `ldd` on both the `.x86` and `.x86_64` and sharing the output. You may also check and share the log at `~/home/<your user name>/.config/unity3d/Nobody's Getting Paid Here/Create Your Frisk/output_log.txt` to see if there is any unusual output.

Finally, if all else fails, download a windows release of CYF and use [Wine](https://www.winehq.org/) to run it on your Linux machine.

**Comment by zeldigas** [comment]
Same problem. x86 behaves exactly the same way. 
Ldd output for x64
```
	linux-vdso.so.1 (0x00007ffc9bdee000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5627aac000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f562788d000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f5627685000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f56272fc000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5626f5e000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f5626d46000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5626955000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f5627cb0000)

```
For x86
```
	linux-vdso.so.1 (0x00007ffc9bdee000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5627aac000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f562788d000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f5627685000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f56272fc000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5626f5e000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f5626d46000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5626955000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f5627cb0000)
```
Logs of 64 execution and contents of file can be found here: https://pastebin.com/0J5TcPZ3

**Comment by zeldigas** [comment]
I found that pressing f4 to exit full screen mode fixes the problem. After that even getting back to full screen mode  works

**Comment by WD200019** [comment]
I may have seen this before. Just did a bit of research. Do you happen to have two monitors? The relevant line is in your pastebin:

> requesting fullscreen 1 x 1 at 0 Hz

This means when CYF initially opens for you, it's opening in fullscreen mode and only showing the very top left pixel of the window.

When I looked this up, I saw some threads from other Unity projects reporting the same thing, mainly on Linux systems with multiple monitors. In addition, given what you reported with pressing F4, the fix may simply be to force CYF to start in windowed mode on Linux (which wouldn't be that bad).

**Comment by daniel071** [comment]
> I found that pressing f4 to exit full screen mode fixes the problem. After that even getting back to full screen mode works

For me pressing f4 didn't work but pressing alt+enter did exit fullscreen successfully, and now I'm able to use CYF

**Comment by daniel071** [comment]
@WD200019 
I've checked if I have any of the packages installed and it seems that I don't however, now that I exited and re-entered fullscreen, it works.

I have the screenshot of `pacman -Q package-name` here if it helps:
![pacman -Q](https://raw.githubusercontent.com/daniel071/images-for-readme/master/Screenshot%20from%202020-02-12%2016-43-49.png)

**Comment by WD200019** [comment]
Should be fixed now. The above commit uses the method I described yesterday - a simple fix to force the game to open in windowed mode if it's being opened for the first ever time. It's important to do it this way because otherwise, there are no calls to `Screen.SetResolution` on the first launch - and it lets Unity pick the resolution, which falters to 1x1 pixels. You said exiting fullscreen restored functionality, and the reason it does that is because going to windowed mode manually calls `Screen.SetResolution(640 * windowScale, 480 * windowScale, false, 0)`.
