### ISSUE TITLE
How do i execute it?

### ISSUE THREAD

**Issue by ImNotAFurryGuy** [RhenaudTheLukark/CreateYourFrisk#72]
i dont know how to execute it, do i need to download something else? or theres a .exe in the folders?

**Comment by TheEternalShine** [comment]
Please make sure you downloaded the window version, if you have a 32 bit computer, download the 32 bit windows version, and if you have a 64 bit computer, download the 64 bit version. you can find the downloads [here](https://github.com/RhenaudTheLukark/CreateYourFrisk/releases/tag/v0.6.5) (you might need to scroll down a bit to find it)

**Comment by RhenaudTheLukark** [comment]
Since no answer has been given, I'll guess the issue has been resolved.
