### ISSUE TITLE
Create your frisk'de Asriel dışında bir karakterle sağdaki köpeği geçmek

### ISSUE THREAD

**Issue by NumaN2004** [RhenaudTheLukark/CreateYourFrisk#73]
**this language is  turkish**

Asriel ile köpeği gönderdikten sonra karakterimi değişmesini sağladım, ben Chara yı seçtim. Ama Create your frisk'in yaratılış hikayesinden sonra çıkan turuncu karakterle konuşurken yine asriel ortaya çıktı bu bir bug mu yoksa henüz yapmadınız mı bilmiyorum ama bence bunu bir başkasında farketmeden yapılması gerek

Platform Windows 7
Version 0.6.5

**Comment by RhenaudTheLukark** [comment]
I'm afraid we can't really help if your issue isn't in English

**Comment by NumaN2004** [comment]
> Korkarım sorununuz İngilizce değilse gerçekten yardımcı olamayız

My problem is english but i dont know enough english

**Comment by NumaN2004** [comment]
> I'm afraid we can't really help if your issue isn't in English

My issue is english but i don't know enough english maybe i try translate with Google translate

**Comment by RhenaudTheLukark** [comment]
I tried it before sending said message, but all it gave me was a mess of words, with no details as to what really is the problem

**Comment by NumaN2004** [comment]
> I tried it before sending said message, but all it gave me was a mess of words, with no details as to what really is the problem

Sorry for that i am new in the github

**Comment by NumaN2004** [comment]
Simply I passed the dog with another character

**Comment by RhenaudTheLukark** [comment]
Now that I'm a bit more free I can answer.

The other Asriel you've seen in there is how one contributor wanted to be shown as in that encounter!

It doesn't have a link at all with the character you're playing, it's not an issue.

I'll leave this issue active for some more if you have any question, but there's nothing bad in there.
