### ISSUE TITLE
help my frisk is in a crate

### ISSUE THREAD

**Issue by Cooliokid956** [RhenaudTheLukark/CreateYourFrisk#74]

**Comment by Dobby233Liu** [comment]
https://github.com/RhenaudTheLukark/CreateYourFrisk/blob/7e1bc67f4e2e453769a216b67e7114edb1e13ac1/Assets/Scripts/Battle/UIController.cs#L901-L904

**Comment by Cooliokid956** [comment]
k
i also just had to beg for MECRY 9+ times
