### ISSUE TITLE
Adds a command called "Misc.RedirectEncounter"

### ISSUE THREAD

**Issue by HzMasterG6** [RhenaudTheLukark/CreateYourFrisk#77]
`Misc.RedirectEncounter( string encounterPathname )`
This command will quit of current encounter and will change to next encounter if `encounterPathname` is nil or will change to encounterPathname to encounter that has this file name.
Results:
- Will throw a error if the encounterPathname is invalid(Trying to change a encounter that does not exist)
- Will clear the temp data and redirect the encounter to "encounterPathname" if valid

Example:
A encounter pack / folder has 3 encounter lua files. 
 **Poseur.lua** , **Posette.lua** and **Team.lua**
If the player kill Poseur.lua the encounter developer can redirect the encounter to Team.lua or Posette.lua calling `Misc.RedirectEncounter("posette.lua")`

**Comment by RhenaudTheLukark** [comment]
Is this a feature request?

**Comment by HzMasterG6** [comment]
> Is this a feature request?

yes

**Comment by RhenaudTheLukark** [comment]
Then I'd rather they happen in the Unitale Discord server, given that I think you're already there.

Second of all, we will most likely not add support for loading an encounter in another encounter, as it would be quite against how CYF works in general.

Meet you on Discord if you want more info on that.
