### ISSUE TITLE
Remove me from 0.5.0_SEE_CRATE

### ISSUE THREAD

**Issue by WD200019** [RhenaudTheLukark/CreateYourFrisk#81]
On November 2nd, 2016, I was added and finalized as part of a secret in Create Your Frisk. I was represented by using Asriel as an avatar, and was referenced by username in dialogue, along with graphics of a petting animation.

I am requesting that I be removed from this secret and no longer appear as a character in Create Your Frisk.  It may seem a bit random to request removal for something added over four years ago now, but due to personal reasons, I'm not comfortable with my portrayal in the 0.5.0 CYF secret anymore.

**Comment by RhenaudTheLukark** [comment]
That's indeed a random request, but sure, I'll do it soon.

**Comment by RhenaudTheLukark** [comment]
It's done, you won't be a part of CYF 0.5's secret anymore in the next version of CYF.
