### ISSUE TITLE
Using the butterscotch pie in the demo overworld freezes the game

### ISSUE THREAD

**Issue by JustAwesomeDanny** [RhenaudTheLukark/CreateYourFrisk#82]
**Describe the bug**
In the demo overworld, if you pick up the butterscotch pie and use it from the ITEM menu it freezes the game, effectively stopping you from closing the menu or doing anything else. No keys respond.

**To Reproduce**
1. Go to the overworld.
2. Pick up the butterscotch pie.
3. Eat it through the ITEM menu.
4. The game freezes.

**Expected behavior**
The game should not freeze, and even though you have full health you should still be able to eat it.

**Setup**
 - OS: Windows
 - Version: 0.6.5
 - Mod: Default overworld

**Comment by RhenaudTheLukark** [comment]
Did you use the current master version of CYF or CYF v0.6.5?

**Comment by JustAwesomeDanny** [comment]
I was using 0.6.5, but if it's been fixed in the master version then I apologise.

**Comment by RhenaudTheLukark** [comment]
Thank you for finding the problem! It was pretty easy to fix so I did it instantly, turns out it was a silliness in the code that was still around on the feature (development) branch.
Thanks for helping me improve the engine!
