### ISSUE TITLE
I can't create a new font

### ISSUE THREAD

**Issue by NumaN2004** [RhenaudTheLukark/CreateYourFrisk#83]
I am trying to make a font with my language but, i am getting an error message
![resim_2021-02-25_094754](https://user-images.githubusercontent.com/68291382/109114366-9374ec80-774e-11eb-8d77-1ef00cf69dd7.png)

**Comment by NumaN2004** [comment]
it is cyf 0.6.4

**Comment by RhenaudTheLukark** [comment]
The error is pretty straightforward. In the font you made, you used the encoding 'iso-8859-9', but it isn't supported.
I suggest you use the encoding 'utf-8' instead, as it seems to have the characters you need.

**Comment by NumaN2004** [comment]
can you tell me which encode formats are supported.

**Comment by NumaN2004** [comment]
I want to use turkish characters.

**Comment by RhenaudTheLukark** [comment]
I don't know the list of encoding formats you can use, but I can assure you the format 'utf-8' works on CYF v0.6.5, as this screenshot shows.
![image](https://user-images.githubusercontent.com/21269430/109208196-52122a80-77aa-11eb-808c-da6cd3db9bb7.png)

**Comment by NumaN2004** [comment]
ok thanks, i will try.

**Comment by RhenaudTheLukark** [comment]
Closing this issue since no extra info has been given.
