### ISSUE TITLE
how do i uninstall this?

### ISSUE THREAD

**Issue by BAPUsesGitHub** [RhenaudTheLukark/CreateYourFrisk#88]
so i did the genocide run and wanted to uninstall it

**Comment by RhenaudTheLukark** [comment]
I suggest you press the button "Erase Almighties" in CYF's Options menu!

**Comment by ultraivan12** [comment]
he literally killed you, rhenny

**Comment by RhenaudTheLukark** [comment]
Don't pollute serious conversations, please. There are other places to do that.
