### ISSUE TITLE
editing dialog messes up compiling

### ISSUE THREAD

**Issue by epicwappy20** [RhenaudTheLukark/CreateYourFrisk#94]
i edited some of the dialog and now it says that its aborting the batch mode because of compiler errors

**Comment by RhenaudTheLukark** [comment]
I'm afraid there's no way I can help without more information.

What is the error you got? What did you modify?

**Comment by epicwappy20** [comment]
i modified the uicontroller for battle and it says "aborting batchmode due to compiler errors" or something like that

**Comment by RhenaudTheLukark** [comment]
This error just means Unity encountered an error while compiling CYF.

Open Unity and try to see what's causing the error.

**Comment by epicwappy20** [comment]
![image](https://user-images.githubusercontent.com/57567782/124475523-d172c480-dd6f-11eb-8b81-d009be5bc6dd.png)

**Comment by RhenaudTheLukark** [comment]
Are you using the right version of Unity? CYF needs a specific version of Unity, which can be found in the docs.

**Comment by epicwappy20** [comment]
ok i compiled it using right version and no exe?!

**Comment by epicwappy20** [comment]
![image](https://user-images.githubusercontent.com/57567782/124502142-e90e7500-dd90-11eb-8fc5-d0edb7177a45.png)
the errors

**Comment by ultraivan12** [comment]
i always use unity 5 for this

**Comment by RhenaudTheLukark** [comment]
I don't know if this has been solved or abandoned, so I'm going to close it for now. Feel free to reopen this issue if there's any more question/problem!
