### ISSUE TITLE
Won't open on Mac

### ISSUE THREAD

**Issue by hAck-3r64** [RhenaudTheLukark/CreateYourFrisk#95]
When I double click or click open from the right-click menu to open CYF 0.6.5, it says "You do not have permission to open the application “Create Your Frisk 0.6.5”." When I go to the 'Get info' menu from the right click menu, it says my permissions are the highest it can be, 'Read and Write', so the official apple article about this doesn't help.

Setup
 - OS: macOS Big Sur
 - Version: 11.4

**Comment by RhenaudTheLukark** [comment]
Right, there are some problems related to how the latest versions of Mac runs CYF apps.

Here's how you can make it work:

In the terminal you cd to the directory CYF is in, and you type the following commands:

    sudo chmod 755 "Create Your Frisk v0.6.5"
    sudo chmod 755 "Create Your Frisk v0.6.5/Contents/MacOS/Create Your Frisk"
    
Then open the program, you get a message that it's unsafe and cannot be run, open it again, and an "open" button will appear on the message.

**Comment by hAck-3r64** [comment]
> Right, there are some problems related to how the latest versions of Mac runs apps.
> 
> Here's how you can make it work:
> 
> In the terminal you cd to the directory CYF is in, and you type the following commands:
> 
> ```
> sudo chmod 755 "Create Your Frisk v0.6.5"
> sudo chmod 755 "Create Your Frisk v0.6.5/Contents/MacOS/Create Your Frisk"
> ```
> 
> Then open the program, you get a message that it's unsafe and cannot be run, open it again, and an "open" button will appear on the message.

This is what happened when I tried: (NOTES: I don't use terminal often and don't understand most of the stuff like this that I need to input, The blocked out parts are just mentions of my name.
<img width="571" alt="Screenshot 2021-07-27 at 17 09 13" src="https://user-images.githubusercontent.com/83057120/127189617-b8690e9a-3b9b-4e17-9f62-469cbc44135a.png">

**Comment by RhenaudTheLukark** [comment]
What this means is that the file doesn't exist. You just need to rename `Create Your Frisk v0.6.5` with whatever the executable name is and it should work!

**Comment by hAck-3r64** [comment]
What do you mean by 'whatever the executable name is'?

**Comment by RhenaudTheLukark** [comment]
Before you tried to open a file to start CYF: this is your executable. You need to replace `Create Your Frisk v0.6.5` in the two commands I gave you with the name of the file you clicked on to try to start CYF.

**Comment by hAck-3r64** [comment]
The name of the file I used to try to open CYF is 'Create Your Frisk 0.6.5', so I don't understand what I have to change.

**Comment by RhenaudTheLukark** [comment]
`Create Your Frisk v0.6.5` and `Create Your Frisk 0.6.5` are different, there's an extra `v` in the command I gave you.

**Comment by hAck-3r64** [comment]
So I would type`sudo chmod 755 "Create Your Frisk 0.6.5"` and `sudo chmod 755 "Create Your Frisk 0.6.5/Contents/MacOS/Create Your Frisk"` into terminal exactly like that?

**Comment by RhenaudTheLukark** [comment]
Exactly, try it out.

**Comment by hAck-3r64** [comment]
Similar errors occurred.

**Comment by hAck-3r64** [comment]
<img width="568" alt="Screenshot 2021-07-27 at 17 26 25" src="https://user-images.githubusercontent.com/83057120/127191988-f54b8818-3d86-42c3-8301-bf44e6fe3ea4.png">

**Comment by RhenaudTheLukark** [comment]
Can you please show me the contents of the folder you're in?

**Comment by hAck-3r64** [comment]
<img width="96" alt="Screenshot 2021-07-27 at 17 30 33" src="https://user-images.githubusercontent.com/83057120/127192219-8f0dbc01-fa4e-4362-a41e-056ead50fa70.png">
<img width="335" alt="Screenshot 2021-07-27 at 17 30 48" src="https://user-images.githubusercontent.com/83057120/127192226-dc7c4d8d-56d3-4f1e-9f2c-ba66c1ff94c0.png">

**Comment by RhenaudTheLukark** [comment]
Well that's weird. Try adding ".app" at the end of the file name in the commands, just in case. That's how those files are shown on Windows.

**Comment by hAck-3r64** [comment]
Such as this? `sudo chmod 755 "Create Your Frisk 0.6.5.app"
`

**Comment by RhenaudTheLukark** [comment]
Yes.

**Comment by hAck-3r64** [comment]
One less error but still no dice.
<img width="570" alt="Screenshot 2021-07-27 at 17 38 40" src="https://user-images.githubusercontent.com/83057120/127193603-c3ae1e84-d421-4e99-863a-59e77c561706.png">

**Comment by RhenaudTheLukark** [comment]
Well try starting CYF with just that, and see if it works. If not, we'll keep fiddling.

**Comment by hAck-3r64** [comment]
:/
<img width="284" alt="Screenshot 2021-07-27 at 17 41 28" src="https://user-images.githubusercontent.com/83057120/127193853-90407a9f-e050-446f-a12c-e569c7039b6c.png">

**Comment by RhenaudTheLukark** [comment]
Do you have an app that allows you to inspect the contents of an app file? Because as you may not know, app files are basically folders.

**Comment by hAck-3r64** [comment]
In the right-click menu there's a 'show package contents' option which I normally use to edit Friday Night Funkin' files, would that work?

**Comment by RhenaudTheLukark** [comment]
That's the one.

**Comment by hAck-3r64** [comment]
What do I do?

**Comment by RhenaudTheLukark** [comment]
Just look for CYF's real executable in the package. It should normally be in the folders Contents/MacOS.

**Comment by hAck-3r64** [comment]
In Contents/MacOS, I found this one file without an extension.
<img width="156" alt="Screenshot 2021-07-27 at 17 46 03" src="https://user-images.githubusercontent.com/83057120/127194689-e8d9b13b-97d5-4d68-abf0-2ab165d25664.png">

**Comment by RhenaudTheLukark** [comment]
There you go. Then in the second command, replace the second `Create Your Frisk` with `Create Your Frisk 0.6.5`, and no need to send the command this time!

**Comment by hAck-3r64** [comment]
It worked! Thank you for dealing with my confusion. 😅

**Comment by RhenaudTheLukark** [comment]
No problem, now I know what commands to send to future users!
